<?php

namespace AppBundle\Repository;

/**
 * ChangeListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangeListRepository extends \Doctrine\ORM\EntityRepository
{
}
